version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: dicesqlserver
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
